name: 배포 파이프라인

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 빌드 단계
  
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: development  # 자동 승인
    steps:
      # 개발 환경 배포 단계
  
  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: staging  # 수동 승인 필요
    steps:
      # 스테이징 환경 배포 단계
  
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production  # 수동 승인 필요
    steps:
      # 프로덕션 환경 배포 단계
