name: Optional Step Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 의존성 설치
        run: npm ci
      
      - name: 린트 검사
        continue-on-error: true
        id: lint
        run: npm run lint
      
      - name: 린트 오류 보고
        if: steps.lint.outcome == 'failure'
        run: |
          echo "::warning::린트 오류가 발견되었습니다. 빌드는 계속 진행됩니다."
          echo "자세한 내용은 로그를 확인하세요."
