name: Pnpm Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: PNPM 설치
        uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: 의존성 설치
        run: pnpm install
      
      - name: 변경된 패키지 빌드
        run: pnpm --filter="...[origin/main]" build
      
      - name: 변경된 패키지 테스트
        run: pnpm --filter="...[origin/main]" test
