name: PR Build and Quality Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]
    types: [ "opened", "synchronize", "reopened" ]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: build-files
          path: dist/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 22]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: build-files
          path: dist/

      - name: Run tests
        run: npm run test:unit