name: Matrix Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkib]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Playwright 설치
        run: npx playwright install --with-deps
      
      - name: 의존성 설치
        run: npm ci
      
      - name: ${{ matrix.browser }} 테스트 실행
        run: npx playwright test --browser=${{ matrix.browser }}
